// Package licenses reports the open source license of every module
// the binary links against. The runtime command reads a CycloneDX
// SBOM that is embedded into the binary at build time (sbom.go), so
// an installed binary needs nothing but itself. The SBOM itself is
// generated by the gen-sbom command, which resolves every dependency
// from the build info and the local module cache (licenses.go,
// cache.go, classify.go) and is deliberately hand-rolled to keep
// the dependency tree small - the same reason config does not use
// viper.
package licenses

import (
	"errors"
	"path/filepath"
	"runtime/debug"
	"sort"
)

// Entry is one dependency with its resolved license.
type Entry struct {
	Module  string
	Version string
	License string // SPDX identifier(s) joined with " / ", or "unknown"
}

// List returns the dependencies from the SBOM embedded at build
// time. It needs no module cache and no build environment - the
// file was baked in by `make sbom`.
func List() ([]Entry, error) {
	return parseSBOM(sbomData)
}

// Resolve determines the licenses of the running binary's
// dependencies the hard way: from the build info and the local
// module cache. It powers the gen-sbom command at build time.
func Resolve() ([]Entry, error) {
	info, ok := debug.ReadBuildInfo()
	if !ok {
		return nil, errors.New("no build info in binary; build with modules")
	}
	cache, err := moduleCache()
	if err != nil {
		return nil, err
	}
	return resolveAll(info, cache), nil
}

// resolveAll maps every dependency of the build info to its license,
// sorted by module path. Split from List so tests can drive it with
// a synthetic build info and a synthetic cache.
func resolveAll(info *debug.BuildInfo, cache string) []Entry {
	entries := make([]Entry, 0, len(info.Deps))
	for _, dep := range info.Deps {
		path, version := dep.Path, dep.Version
		if dep.Replace != nil {
			path, version = dep.Replace.Path, dep.Replace.Version
		}
		entries = append(entries, Entry{
			Module:  path,
			Version: version,
			License: resolve(cache, path, version),
		})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Module < entries[j].Module })
	return entries
}

// resolve finds the license of one module in the cache and
// classifies it. A missing cache entry, missing license file, or
// unrecognized text all yield "unknown" rather than an error - a
// licenses listing should degrade, not fail.
func resolve(cache, path, version string) string {
	if version == "" {
		return "unknown"
	}
	dir := filepath.Join(cache, cachePath(path)+"@"+version)
	text, ok := licenseText(dir)
	if !ok {
		return "unknown"
	}
	return classify(text)
}
