package licenses

import (
	"bytes"
	_ "embed"
	"fmt"
	"sort"
	"strings"

	"github.com/CycloneDX/cyclonedx-go"
)

// sbomData is the CycloneDX document baked in at build time. It is
// generated by `go-reins gen-sbom` and refreshed via `make sbom`;
// it is committed so a plain `go build` works without make. The
// document uses the official cyclonedx-go schema types; only the
// license resolution is hand-rolled.
//
//go:embed sbom.json
var sbomData []byte

// WriteCycloneDX renders the SBOM for product and entries as
// pretty-printed CycloneDX JSON. The metadata carries no timestamp
// on purpose - regeneration must be byte-for-byte reproducible, or
// the staleness check in `make check` could not work.
func WriteCycloneDX(product string, entries []Entry) ([]byte, error) {
	components := make([]cyclonedx.Component, 0, len(entries))
	for _, e := range entries {
		licenses := cyclonedx.Licenses{
			{Expression: licenseExpression(e.License)},
		}
		components = append(components, cyclonedx.Component{
			Type:       cyclonedx.ComponentTypeLibrary,
			Name:       e.Module,
			Version:    e.Version,
			PackageURL: fmt.Sprintf("pkg:golang/%s@%s", e.Module, e.Version),
			Licenses:   &licenses,
		})
	}

	bom := cyclonedx.NewBOM()
	bom.Metadata = &cyclonedx.Metadata{
		Component: &cyclonedx.Component{
			Type: cyclonedx.ComponentTypeApplication,
			Name: product,
		},
	}
	bom.Components = &components

	var buf bytes.Buffer
	enc := cyclonedx.NewBOMEncoder(&buf, cyclonedx.BOMFileFormatJSON)
	enc.SetPretty(true)
	if err := enc.Encode(bom); err != nil {
		return nil, fmt.Errorf("encode cyclonedx: %w", err)
	}
	return buf.Bytes(), nil
}

// licenseExpression turns the display form ("Apache-2.0 / MIT") into
// a single SPDX expression ("Apache-2.0 OR MIT"); an unknown license
// becomes NOASSERTION, the SPDX way to say "present but unknown".
func licenseExpression(license string) string {
	if license == "unknown" {
		return "NOASSERTION"
	}
	return strings.ReplaceAll(license, " / ", " OR ")
}

// parseSBOM reads the embedded document back into entries, sorted by
// module path. It accepts both the expression form this tool writes
// and the bare-id form other generators commonly produce.
func parseSBOM(data []byte) ([]Entry, error) {
	var bom cyclonedx.BOM
	if err := cyclonedx.NewBOMDecoder(bytes.NewReader(data), cyclonedx.BOMFileFormatJSON).Decode(&bom); err != nil {
		return nil, fmt.Errorf("parse embedded sbom: %w", err)
	}
	if bom.BOMFormat != "CycloneDX" {
		return nil, fmt.Errorf("embedded sbom: format %q, want CycloneDX", bom.BOMFormat)
	}
	if bom.Components == nil {
		return nil, fmt.Errorf("embedded sbom: no components")
	}

	entries := make([]Entry, 0, len(*bom.Components))
	for _, c := range *bom.Components {
		entries = append(entries, Entry{
			Module:  c.Name,
			Version: c.Version,
			License: componentLicense(c),
		})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Module < entries[j].Module })
	return entries, nil
}

// componentLicense flattens the license declarations of one
// component back into the display form. NOASSERTION - the SPDX wire
// form this tool writes for unknown licenses - decodes back to
// "unknown" so a write/parse roundtrip is symmetric.
func componentLicense(c cyclonedx.Component) string {
	if c.Licenses == nil {
		return "unknown"
	}
	var found []string
	for _, l := range *c.Licenses {
		switch {
		case l.Expression != "":
			if l.Expression == "NOASSERTION" {
				found = append(found, "unknown")
				continue
			}
			found = append(found, strings.ReplaceAll(l.Expression, " OR ", " / "))
		case l.License != nil:
			found = append(found, l.License.ID)
		}
	}
	if len(found) == 0 {
		return "unknown"
	}
	return strings.Join(found, " / ")
}
